/**
 * Single source of truth for all snippet features.
 * Must match the "feature" field in server/src/data/snippets (all JSON files).
 */

export const FEATURES = [
  'accordion',
  'animation',
  'api',
  'auth',
  'breadcrumb',
  'buttons',
  'cache',
  'card',
  'carousel',
  'class',
  'context',
  'crud',
  'debounce',
  'dto',
  'dropdown',
  'email',
  'event',
  'exception',
  'fetch',
  'flexbox',
  'form',
  'formik',
  'gradient',
  'grid',
  'hooks',
  'input',
  'joins',
  'keyframes',
  'layout',
  'media-queries',
  'middleware',
  'model',
  'modal',
  'navbar',
  'observer',
  'pagination',
  'promise',
  'query',
  'redux',
  'repository',
  'responsive',
  'router',
  'service',
  'shadow',
  'slider',
  'storage',
  'stored-procedures',
  'stream',
  'table',
  'tabs',
  'tooltip',
  'transforms',
  'transactions',
  'transitions',
  'triggers',
  'upload',
  'validation',
  'variables',
  'views',
  'websocket',
] as const;

export type FeatureType = (typeof FEATURES)[number];
