/**
 * Icônes (emoji) par feature pour l'affichage dans le sélecteur de snippets.
 * Une seule source pour éviter la duplication ; évolution possible : JSON chargé à la demande.
 */

export const DEFAULT_FEATURE_ICON = '📄';

export const FEATURE_ICONS: Record<string, string> = {
  form: '📝',
  input: '📥',
  layout: '📐',
  modal: '🪟',
  navbar: '🧭',
  card: '🃏',
  table: '📊',
  slider: '🎠',
  accordion: '📑',
  animation: '🎬',
  responsive: '📱',
  flexbox: '📦',
  grid: '🔲',
  buttons: '🔘',
  variables: '🎨',
  transforms: '🔄',
  api: '🌐',
  validation: '✅',
  fetch: '🔄',
  storage: '💾',
  debounce: '⚡',
  promise: '🔮',
  observer: '👁️',
  event: '🎯',
  class: '🏛️',
  crud: '🏗️',
  model: '📋',
  service: '⚙️',
  repository: '🗄️',
  dto: '📦',
  router: '🛣️',
  middleware: '🔒',
  auth: '🔐',
  query: '📊',
  joins: '🔗',
  transactions: '🔄',
  indexes: '📈',
  views: '👁️',
  breadcrumb: '🍞',
  dropdown: '📑',
  tabs: '📑',
  tooltip: '💬',
  pagination: '📄',
  carousel: '🎠',
  keyframes: '🎬',
  gradient: '🌈',
  shadow: '🎭',
  transitions: '🔄',
  'media-queries': '📱',
  hooks: '🪝',
  context: '🔄',
  redux: '🔄',
  formik: '📋',
  websocket: '📡',
  cache: '💾',
  email: '📧',
  upload: '📤',
  exception: '⚠️',
  stream: '🌊',
  triggers: '⚡',
  'stored-procedures': '📦',
};

export function getFeatureIcon(feature: string): string {
  return FEATURE_ICONS[feature] ?? DEFAULT_FEATURE_ICON;
}
